server:
  port: 8100
spring:
  application:
    name: order-service
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#https://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.0.4.RELEASE/single/spring-cloud-netflix.html#_customizing_the_ribbon_client_by_setting_properties
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule