server:
  port: 9100
spring:
  application:
    name: api-gateway
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignoredServices: '*'
  routes:
    product-service: /apigateway/product/**
    order-service: /apigateway/order/**