server:
  port: 8090
spring:
  application:
    name: product-service
eureka:
  instance:
    hostname: localhost
    non-secure-port: ${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/